builds:
- env:
  - CGO_ENABLED=0
  ldflags:
  - -s
  - -w
  - -X github.com/stern/stern/cmd.version={{.Version}}
  - -X github.com/stern/stern/cmd.commit={{.Commit}}
  - -X github.com/stern/stern/cmd.date={{.Date}}
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm
  - arm64
archives:
- builds:
  - stern
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  format: tar.gz
  files:
  - LICENSE
  wrap_in_directory: false
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
dockers:
- image_templates:
  - "ghcr.io/stern/stern:latest"
  - "ghcr.io/stern/stern:{{ .Major }}"
  - "ghcr.io/stern/stern:{{ .Major }}.{{ .Minor }}"
  - "ghcr.io/stern/stern:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
krews:
- skip_upload: true
  homepage: https://github.com/stern/stern
  description: |
    Stern allows you to `tail` multiple pods on Kubernetes and multiple containers
    within the pod. Each result is color coded for quicker debugging.

    The query is a regular expression so the pod name can easily be filtered and
    you don't need to specify the exact id (for instance omitting the deployment
    id). If a pod is deleted it gets removed from tail and if a new pod is added it
    automatically gets tailed.

    When a pod contains multiple containers Stern can tail all of them too without
    having to do this manually for each one. Simply specify the `container` flag to
    limit what containers to show. By default all containers are listened to.
  short_description: Multi pod and container log tailing
